version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    environment:
      - ORACLE_PASSWORD=SysPassword1
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521:XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=SysPassword1
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1555:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  oracle_data:
